import * as React from 'react';
import Head from 'next/head';
import Header from '@/components/Common/Header';
import MyPage from '@/components/MyPage';

const mypage = () => {
  return (
    <>
      <Head>
        <title>MyPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MyPage />
    </>
  )
}

export default mypage;