import Rect from 'react';
import Head from 'next/head';
import Header from '@/components/Common/Header';
import Ticket from '@/components/Ticket';
import Footer from '@/components/Common/Footer';

const TicketPage = () => {

  return (
    <>
      <Head>
        <title>Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Ticket />
      {/* <Footer /> */}
    </>
  )
}

export default TicketPage;