name: Automerge and Create Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge to Dev
        run: |
          git fetch origin dev
          git checkout dev
          git merge --no-ff ${{ github.ref }}
          git push origin dev

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'Merge dev to main'
